version: '3.7'

services:

  web:
    build: apache/
    container_name: web
    restart: always
    privileged: true
    ports:
      - "80:80"
      - "8000:8000"
      - "3000:3000"
      - "443:443"
      - "22:22"
    volumes:
      - ./web:/var/www/html
    links:
      - "mysql"

  mysql:
    build: mysql/
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_HOST: 127.0.0.1:3306
      MYSQL_USER: root
  
  phpmyadmin:
    build: phpmyadmin/
    container_name: phpmyadmin
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    volumes:
      - ./phpmyadmin/upload.ini:/usr/local/etc/php/php.ini